In [1]:
import numpy as np

In [8]:
data = np.array([23.3,23,56,44,34 ,23,48,11,56,34,14,35,67,89,12,43,23,32,54,65,76,56,33,32,32,54,64,34,21,20,19])
length2 = len(data)
print(length2)

31


In [3]:
week = data[:8]
print(week)

[23.3 23.  56.  44.  34.  48. ]


In [7]:
week2 = data[8:15]
week3 = data[15:23]
week4 = data[22:31]
print(week2)
print(week3)
print(week4)

[56. 34. 14. 35. 67. 89. 12.]
[43. 23. 32. 54. 65. 76. 56. 33.]
[33. 32. 32. 54. 64. 34. 21. 20. 19.]


In [10]:
hot_days = data[data > 30]
print(hot_days)

[56. 44. 34. 48. 56. 34. 35. 67. 89. 43. 32. 54. 65. 76. 56. 33. 32. 32.
 54. 64. 34.]


In [18]:
cold_day = data[data < 30]
print(cold_day)

[23.3 23.  23.  11.  14.  12.  23.  21.  20.  19. ]


In [29]:
length1 = len(hot_days)
print(length1)

21


In [26]:
length3 = len(cold_day)
print(length3)

10


In [27]:
percentage_hotdays = (length1/length2)*(100)
print(percentage_hotdays)

67.74193548387096


In [31]:
percentage_colddays = (length3/length2)*(100)
print(percentage_colddays)

32.25806451612903
