In [7]:
import numpy as np

In [8]:
array = np.array([12,14,5,6,2,7,12,24,7,10,12,23])
print(array.reshape(3,4))

[[12 14  5  6]
 [ 2  7 12 24]
 [ 7 10 12 23]]


In [9]:
array.reshape(3,4).T

array([[12,  2,  7],
       [14,  7, 10],
       [ 5, 12, 12],
       [ 6, 24, 23]])

In [10]:
student_data = np.random.randint(10,20,(10,5))
print(student_data)

[[18 16 11 18 19]
 [13 19 11 19 14]
 [19 15 12 10 13]
 [18 11 10 11 11]
 [12 13 18 19 18]
 [12 11 18 15 19]
 [14 10 19 10 17]
 [18 17 15 16 10]
 [19 10 19 14 10]
 [11 18 10 14 11]]


In [11]:
student_avg = student_data.mean(axis=1)

print(student_avg)

[16.4 15.2 13.8 12.2 16.  15.  14.  15.2 14.4 12.8]


In [12]:
marks_avg = student_data.mean(axis=0)
print(marks_avg)

[15.4 14.  14.3 14.6 14.2]


In [13]:
print(student_data.std())

3.4190641994557516


In [14]:
dice = np.random.randint(1,7,1000)
total_outcome = np.bincount(dice)[1:]   # bin count is a fuction which tells us koi number kitne baar aa rhsa hai 
print(total_outcome)

[178 159 193 154 140 176]


In [15]:
sensor_reading = np.array([1,2,np.nan,4,np.nan])
print(np.isnan(sensor_reading).sum())

2


In [16]:
np.where(np.isnan(sensor_reading),np.nanmean(sensor_reading),sensor_reading)

array([1.        , 2.        , 2.33333333, 4.        , 2.33333333])

In [17]:
filtered = np.isnan(sensor_reading)
print(filtered)

[False False  True False  True]
